### PR TITLE
Course iterator implementation

### PR DESCRIPTION
**Pull request by tomaskodym**
Hello I have prepared the implementation of the course Iterator and corresponding tests.

I would like to ask you if you could check it.

Thank you in advance.
Tomáš Kodym

### CODE REVIEW

**Comment by bLuma** [comment]
I think that it will be better if You throw up UnsupportedOperationException on calling remove on iterator object.

**Comment by tomaskodym** [comment]
Hello,
I have done changes as you mentioned in comment above. 
I would like to ask you if you could check it.

Thank you,
Tomáš Kodym

**Comment by bLuma** [comment]
Doesn't work - Arrays.asList returns fixed-size array - no modifications are futher possible and you're trying to add items.

Simple unmodifiableList from Collections 
 will be enough - https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#unmodifiableList(java.util.List)

**Comment by tomaskodym** [comment]
Hello, I have done changes as you mentioned.
Could you please check it?

Thank you in advance.
Tomáš Kodym

**Comment by bLuma** [comment]
Please read your iterator method once more and check where your exception raises...

**Comment by tomaskodym** [comment]
Hello, 
Sorry, I did not notice this issue before, because the same exception was thrown.
I have made some changes and the exception is now thrown in remove block.
Could you please check it? 

Please let me know, if any other changes are necessary.

Thank you in advance.
Tomáš Kodym

**Pull request merged**
