### PR TITLE
Implementing ISchool #1

### PR DESCRIPTION
**Pull request by nomad-cc20**
Class School now implements the interface ISchool. Method addStudent in School defined with a corresponding test.

### CODE REVIEW

**Review by bLuma — CHANGES_REQUESTED** [review]
Your tests are unnecessarily too much complicated. You don't really need stream(), please follow standard unit test guidelines.

**Comment by nomad-cc20** [comment]
Tests got simplified.

**Comment by bLuma** [comment]
You are reverting useful checks in addCourse method. Please fix this before merging.

**Comment by nomad-cc20** [comment]
Okay, I was a bit late of recent commits. The project got updated with your master branch.

**Pull request merged**
